<?php

/**
 * @file
 * LocalGov Drupal Microsites Media module hooks.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\group\Access\GroupAccessResult;

/**
 * Implements hook_ENTITY_TYPE_create_access() for node entities.
 */
function localgov_microsites_media_node_create_access(AccountInterface $account, array $context, $entity_bundle) {

  // Allow group users to add media items to new nodes.
  $group = localgov_microsites_group_get_by_context();
  if ($group) {
    $permission = 'create group_node:' . $entity_bundle . ' entity';
    return GroupAccessResult::allowedIfHasGroupPermissions($group, $account, [$permission], 'AND');
  }

}
